<?xml version="1.0"?>
<robot name="pipe_sprite" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find pipe_description)/urdf/materials.xacro"/>
    <!-- <xacro:include filename="$(find pipe_sprite_description)/urdf/pipesprite.gazebo"/> -->
    <xacro:include filename="$(find pipe_description)/urdf/pipesprite.trans"/>

    <xacro:property name="base_length" value="0.5"/>
    <xacro:property name="base_width" value="0.23"/>
    <xacro:property name="base_height" value="0.1"/>

    <xacro:property name="base_density" value="1"/>    <!-- Approx. density -->
    <xacro:property name="base_mass" value="${base_density*base_length*base_width*base_height}"/>

    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_separation" value="${base_width + wheel_width}"/>
    <xacro:property name="wheel_offset" value="${base_length/2 - wheel_radius + .085}"/>

    <xacro:property name="wheel_density" value="100"/>    <!-- Approx. density -->
    <xacro:property name="wheel_mass" value="${wheel_density*(pi*wheel_radius*wheel_radius)*wheel_width}"/>

    <xacro:property name="wheel_joint_rotation" value="1.15"/>

    <xacro:property name="base_ixx" value="${base_mass*(base_width*base_width+base_height*base_height)/12}"/>
    <xacro:property name="base_ixy" value="0.000"/>
    <xacro:property name="base_ixz" value="0.000"/>
    <xacro:property name="base_iyy" value="${base_mass*(base_length*base_length+base_height*base_height)}"/>
    <xacro:property name="base_iyz" value="0.00"/>
    <xacro:property name="base_izz" value="${base_mass*(base_length*base_length+base_height*base_height)}"/>

    <xacro:property name="wheel_ixx" value="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}"/>
    <xacro:property name="wheel_ixy" value="0.000"/>
    <xacro:property name="wheel_ixz" value="0.000"/>
    <xacro:property name="wheel_iyy" value="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}"/>
    <xacro:property name="wheel_iyz" value="0.00"/>
    <xacro:property name="wheel_izz" value="${wheel_mass*wheel_radius*wheel_radius/2}"/>

    <link name="base_footprint"/>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 -.08" rpy="0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://pipe_sprite_description/meshes/pipe_sprite_base.stl" scale="0.005 0.005 0.005"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 -.08" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://pipe_sprite_description/meshes/pipe_sprite_base.stl" scale="0.005 0.005 0.005"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.001 0.001 0.001" rpy="0 0 0"/>
            <mass value="${base_mass}"/>
            <inertia ixx="${base_ixx}" ixy="${base_ixy}" ixz="${base_ixz}"
                iyy="${base_iyy}" iyz="${base_iyz}" izz="${base_izz}"/>
        </inertial>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <!-- Left Rear Wheel -->
    <link name="left_rear_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="dark_grey"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.001 0.001 0.001" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}"
                iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}"/>
        </inertial>
    </link>

    <!-- Left Front Wheel -->
    <link name="left_front_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="dark_grey"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.001 0.001 0.001" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}"
                iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}"/>
        </inertial>
    </link>


    <!-- Right Rear Wheel -->
    <link name="right_rear_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="dark_grey"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.001 0.001 0.001" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}"
                iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}"/>
        </inertial>
    </link>

    <!-- Right Front Wheel -->
    <link name="right_front_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="dark_grey"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.001 0.001 0.001" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}"
                iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}"/>
        </inertial>
    </link>

    <!-- Left Rear Wheel Joint -->
    <joint name="left_rear_wheel_joint" type="continuous">
        <origin xyz="-${wheel_offset} ${wheel_separation/2} -${wheel_radius/2}" rpy="-${wheel_joint_rotation} 0 0"/>
        <parent link="base_link"/>
        <child link="left_rear_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Left Front Wheel Joint -->
    <joint name="left_front_wheel_joint" type="continuous">
        <origin xyz="${wheel_offset} ${wheel_separation/2} -${wheel_radius/2}" rpy="-${wheel_joint_rotation} 0 0"/>
        <parent link="base_link"/>
        <child link="left_front_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Right Rear Wheel Joint -->
    <joint name="right_rear_wheel_joint" type="continuous">
        <origin xyz="-${wheel_offset} ${-wheel_separation/2} -${wheel_radius/2}" rpy="${wheel_joint_rotation} 0 0"/>
        <parent link="base_link"/>
        <child link="right_rear_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Right Front Wheel Joint -->
    <joint name="right_front_wheel_joint" type="continuous">
        <origin xyz="${wheel_offset} ${-wheel_separation/2} -${wheel_radius/2}" rpy="${wheel_joint_rotation} 0 0"/>
        <parent link="base_link"/>
        <child link="right_front_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit effort="100" velocity="10.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Camera -->
    <link name="camera_visual_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi}"/>
            <geometry>
                <cylinder radius="0.025" length="0.02"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi}"/>
            <geometry>
                <cylinder radius="0.025" length="0.02"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.005"/>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi}"/>
            <inertia ixx="5e-5" ixy="0" ixz="0" iyy="5e-5" iyz="0" izz="5e-5"/>
        </inertial>
    </link>

    <joint name="camera_visual_joint" type="fixed">
        <axis xyz="0 1 0"/>
        <origin xyz=".27 0 .22" rpy="0 0 ${-pi}"/>
        <parent link="base_link"/>
        <child link="camera_visual_link"/>
    </joint>

    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.001" length="0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.025" length="0.02"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.005"/>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <inertia ixx="5e-5" ixy="0" ixz="0" iyy="5e-5" iyz="0" izz="5e-5"/>
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <axis xyz="0 1 0"/>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <parent link="camera_visual_link"/>
        <child link="camera_link"/>
    </joint>

    <!-- Laser -->
    <link name="laser_rod_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.007" length=".15"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.01" length=".7"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.005"/>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <inertia ixx="5e-5" ixy="0" ixz="0" iyy="5e-5" iyz="0" izz="5e-5"/>
        </inertial>
    </link>

    <joint name="laser_rod_joint" type="fixed">
        <axis xyz="0 1 0"/>
        <origin xyz=".30 -.04 .19" rpy="0 0 ${-pi}"/>
        <parent link="base_link"/>
        <child link="laser_rod_link"/>
    </joint>

    <link name="laser_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.001" length=".001"/>
            </geometry>
            <material name="dark_grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="0.01" length=".7"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.005"/>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <inertia ixx="5e-5" ixy="0" ixz="0" iyy="5e-5" iyz="0" izz="5e-5"/>
        </inertial>
    </link>

    <joint name="laser_joint" type="fixed">
        <axis xyz="0 1 0"/>
        <origin xyz="-.08 0.0 0.0" rpy="0 0 ${-pi}"/>
        <parent link="laser_rod_link"/>
        <child link="laser_link"/>
    </joint>

    <!-- IMU -->
    <link name="imu_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.015 0.0075 0.0025"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.015 0.0075 0.0025"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <mass value="0.003"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="5e-5" ixy="0" ixz="0" iyy="5e-5" iyz="0" izz="5e-5"/>
        </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
        <axis xyz="0 1 0"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

</robot>